import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnInit,
  ViewChild,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import html2canvas from 'html2canvas'; // Import html2canvas
import { environment } from '../../environments/environment';
import { BookingService } from '../services/booking.service';
import { CompanyService } from '../services/company.service';
import { FormService } from '../services/form.service';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-receipt',
  templateUrl: './receipt.page.html',
  styleUrls: ['./receipt.page.scss'],
})
export class ReceiptPage implements OnInit, AfterViewInit {
  @ViewChild('receiptContent') receiptContent!: ElementRef; // Reference to the content to capture
  receiptId: any;
  receipt: any;
  pdfUrl: string = '';

  testAPI = environment.API;
  localAPI = 'http://localhost:3000';
  uid: any; // Store the user ID
  user: any; // Object to hold user data
  companyProfile: any = null;
  private loadedCompanyId: number | null = null;
  private userReady = false;
  private viewReady = false;
  private receiptReady = false;
  private autoGenerated = false;

  constructor(
    private activatedRoute: ActivatedRoute,
    private userService: UserService,
    private bookingService: BookingService,
    private companyService: CompanyService,
    private formService: FormService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit() {
    this.uid = localStorage.getItem('uid'); // Retrieve user ID from local storage

    this.activatedRoute.params.subscribe((params) => {
      this.receiptId = params['receipt_id'];

      console.log('Received ID:', this.receiptId);
      if (this.receiptId) {
        this.loadReceipt();
      } else {
        console.log('receipt id not found');

        // this.errorMessage = 'Receipt ID not found.';
        // this.isLoading = false;  // Hide loading spinner
      }
    });

    // this.loadForm();
    this.loadUser();
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
    this.tryAutoGenerateReceipt();
  }

  loadUser() {
    if (this.uid) {
      this.userService.getUserByID(this.uid).subscribe(
        (response) => {
          this.user = this.unwrapPayload(response);
          this.loadCompanyProfile(this.user?.company_id);
          this.userReady = true;
          this.tryAutoGenerateReceipt();
        },
        (error) => {
          console.log(error);
          this.userReady = true;
          this.tryAutoGenerateReceipt();
        },
      );
    } else {
      console.log('uid not found in storage');
      this.userReady = true;
      this.tryAutoGenerateReceipt();
    }
  }

  // ngAfterViewInit(): void {
  //   // Now, you can safely use this.receiptContent
  //   // console.log(this.receiptContent);  // To make sure it's assigned
  //   // this.generateReceipt();
  //   if (this.receipt) {
  //     this.generateReceipt();  // Generate the PDF after form is loaded
  //   }
  // }

  //get receipt details
  loadReceipt() {
    if (this.receiptId) {
      const stateBooking = history.state?.['booking'] ?? null;
      if (stateBooking) {
        this.receipt = this.mapBookingToReceipt(stateBooking);
        this.loadCompanyProfile(this.receipt?.company_id);
        this.receiptReady = true;
        this.tryAutoGenerateReceipt();
        return;
      }

      this.bookingService.getBookingById(this.receiptId).subscribe(
        (response) => {
          const data = response?.data || response;
          if (data?.booking_type) {
            this.receipt = this.mapBookingToReceipt(data);
            this.loadCompanyProfile(this.receipt?.company_id);
            this.receiptReady = true;
            this.tryAutoGenerateReceipt();
            return;
          }

          this.formService.getFormByID(this.receiptId).subscribe(
            (legacyResponse) => {
              this.receipt = legacyResponse.data || legacyResponse;
              this.loadCompanyProfile(this.receipt?.company_id);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
            (error) => {
              console.log(error);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
          );
        },
        (error) => {
          console.log(error);
          this.formService.getFormByID(this.receiptId).subscribe(
            (legacyResponse) => {
              this.receipt = legacyResponse.data || legacyResponse;
              this.loadCompanyProfile(this.receipt?.company_id);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
            (legacyError) => {
              console.log(legacyError);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
          );
        },
      );
    } else {
      console.log('uid not found in storage');
    }
  }

  pdfLink: string = '';
  qrCodeReady: boolean = false;

  generateQR() {
    if (this.pdfUrl) {
      const pdfPath = this.pdfUrl.startsWith('http')
        ? this.pdfUrl
        : `${this.testAPI}${this.pdfUrl}`;
      this.pdfLink = pdfPath;
      this.qrCodeReady = true;
      this.cdr.detectChanges();
      console.log('Generating QR code with URL:', this.pdfLink);
    } else {
      alert('Error Generating PDF');
      console.log('No URL for QR code generation');
    }
  }

  getImageDataUrl(image: HTMLImageElement): string {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (ctx) {
      canvas.width = image.width;
      canvas.height = image.height;
      ctx.drawImage(image, 0, 0);
      return canvas.toDataURL('image/png');
    }
    return '';
  }

  // Method to generate the receipt PDF
  async generateReceipt() {
    const receiptElement = this.receiptContent?.nativeElement as
      | HTMLElement
      | undefined;
    if (!receiptElement) {
      alert('Error Generating PDF');
      console.error('Receipt element not found for capture');
      return;
    }

    const captureElement = this.createCaptureClone(receiptElement);
    document.body.appendChild(captureElement);

    try {
      await this.waitForImages(captureElement);
    } catch (waitError) {
      console.warn(
        'Image wait timed out, continuing capture anyway',
        waitError,
      );
    }

    // Use html2canvas to capture a screenshot of the element
    html2canvas(captureElement, {
      ignoreElements: (element) => {
        const tag = String(element?.tagName || '').toLowerCase();
        return (
          element.classList.contains('qr-btn') ||
          tag === 'ion-loading' ||
          tag === 'ion-backdrop' ||
          tag === 'ion-alert' ||
          tag === 'ion-toast' ||
          tag === 'ion-modal' ||
          tag === 'ion-popover'
        );
      },
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      scale: 2,
      imageTimeout: 15000,
    })
      .finally(() => {
        captureElement.remove();
      })
      .then((canvas) => {
        canvas.toBlob((blob) => {
          if (blob) {
            // Prepare FormData to send the image file to the backend
            const formData = new FormData();
            formData.append('receiptImage', blob, 'receipt.png'); // Append Blob as file
            formData.append('receiptId', this.receiptId); // append receipt id as req

            // Send the formData to the backend API to generate the PDF
            this.formService.generatePdfFromImage(formData).subscribe(
              (response: any) => {
                if (response.success) {
                  this.pdfUrl = response.fileUrl; // Save the returned PDF URL
                  this.generateQR(); // generate the QR Code
                  console.log('PDF URL:', this.pdfUrl);
                } else {
                  alert('Error Generating PDF');
                  console.error('Failed to generate PDF', response);
                }
              },
              (error) => {
                alert('Error Generating PDF');
                console.error('Error generating PDF', {
                  status: error?.status,
                  message: error?.message,
                  error: error?.error,
                });
              },
            );
          } else {
            alert('Error Generating PDF');
            console.error('Failed to capture canvas as Blob');
          }
        }, 'image/png'); // Convert the canvas to a Blob in PNG format
      })
      .catch((error) => {
        alert('Error Generating PDF');
        console.error('Error capturing receipt:', {
          message: error?.message,
          stack: error?.stack,
          error,
        });
      });
  }

  private mapBookingToReceipt(record: any): any {
    const totalRooms =
      Number(record?.total_pax || 0) ||
      Number(record?.domesticPax || record?.no_of_pax_domestik || 0) +
        Number(record?.internationalPax || record?.no_of_pax_antarbangsa || 0);

    const receiptId =
      record?.numericId ?? record?.id ?? this.receiptId ?? undefined;

    return {
      receipt_id: String(receiptId || ''),
      createdAt:
        record?.receipt_created_at ||
        record?.updated_at ||
        record?.created_at ||
        record?.updatedAt ||
        record?.createdAt,
      company_id: Number(record?.company_id ?? record?.companyId ?? 0) || null,
      guest_name: String(
        record?.tourist_full_name ||
          record?.fullName ||
          record?.tourist_name ||
          record?.user_fullname ||
          record?.userFullname ||
          '',
      ),
      accommodation_name: String(
        record?.product_name || record?.productName || record?.homestay || '',
      ),
      check_in_date: record?.check_in_date || record?.checkInDate || null,
      check_out_date: record?.check_out_date || record?.checkOutDate || null,
      total_night: Number(record?.total_of_night ?? record?.nights ?? 0),
      total_rooms: totalRooms,
      status: String(record?.status || 'paid'),
      total_rm: Number(record?.total_price ?? record?.totalAmount ?? 0),
      company_name: String(
        record?.company_name ||
          record?.companyName ||
          record?.company?.company_name ||
          '',
      ),
      operator: {
        business_name: String(
          record?.company_name ||
            record?.companyName ||
            record?.operator_name ||
            record?.operatorName ||
            '',
        ),
        full_name: String(
          record?.operator_name ||
            record?.operatorName ||
            record?.user_fullname ||
            record?.userFullname ||
            '',
        ),
        user_email: String(
          record?.company_email ||
            record?.companyEmail ||
            record?.operatorEmail ||
            this.user?.user_email ||
            this.user?.email ||
            '',
        ),
      },
    };
  }

  get bookedByName(): string {
    return String(
      this.receipt?.guest_name ||
        this.receipt?.tourist_full_name ||
        this.receipt?.tourist_name ||
        'N/A',
    );
  }

  get companyName(): string {
    return String(
      this.companyProfile?.company_name ||
        this.receipt?.company_name ||
        this.user?.business_name ||
        this.user?.company?.company_name ||
        this.receipt?.operator?.business_name ||
        'N/A',
    );
  }

  get companyEmail(): string {
    return String(
      this.companyProfile?.email ||
        this.user?.company?.email ||
        this.user?.user_email ||
        this.user?.email ||
        this.receipt?.operator?.user_email ||
        'N/A',
    );
  }

  get companyLogoUrl(): string {
    const source =
      this.companyProfile?.operator_logo_image ||
      this.user?.company_logo ||
      this.user?.company?.operator_logo_image ||
      '';
    return this.resolveImageSource(source, '../../assets/icon/RuralT Logo.png');
  }

  private createCaptureClone(sourceElement: HTMLElement): HTMLElement {
    const clone = sourceElement.cloneNode(true) as HTMLElement;
    clone.classList.add('receipt-capture-clone');
    clone.style.position = 'fixed';
    clone.style.left = '-10000px';
    clone.style.top = '0';
    // Force capture to a narrow portrait card width so the PDF shows a vertical card
    clone.style.width = '520px';
    clone.style.pointerEvents = 'none';
    clone.style.opacity = '1';

    clone
      .querySelectorAll('ion-button, qrcode, ion-header, ion-content')
      .forEach((el) => {
        el.remove();
      });

    clone.querySelectorAll('img').forEach((img) => {
      const source = (img as HTMLImageElement).getAttribute('src') || '';
      if (source) {
        (img as HTMLImageElement).crossOrigin = 'anonymous';
      }
    });

    const footerButton = clone.querySelector('.receipt-footer-button');
    if (footerButton) {
      footerButton.remove();
    }

    return clone;
  }

  private waitForImages(container: HTMLElement): Promise<void> {
    const images = Array.from(
      container.querySelectorAll('img'),
    ) as HTMLImageElement[];
    if (images.length === 0) {
      return Promise.resolve();
    }

    return Promise.race([
      Promise.all(
        images.map(
          (img) =>
            new Promise<void>((resolve) => {
              if (img.complete && img.naturalWidth > 0) {
                resolve();
                return;
              }
              img.onload = () => resolve();
              img.onerror = () => resolve();
            }),
        ),
      ).then(() => undefined),
      new Promise<void>((resolve) => setTimeout(resolve, 5000)),
    ]);
  }

  private unwrapPayload(response: any): any {
    return response?.data || response;
  }

  private loadCompanyProfile(companyId: any): void {
    const normalizedId = Number(companyId);
    if (!Number.isInteger(normalizedId) || normalizedId <= 0) {
      return;
    }
    if (this.loadedCompanyId === normalizedId) {
      return;
    }

    this.loadedCompanyId = normalizedId;
    this.companyService.getCompanyById(normalizedId).subscribe(
      (response) => {
        this.companyProfile = this.unwrapPayload(response);
      },
      (error) => {
        console.error('Error loading company profile:', error);
      },
    );
  }

  private resolveImageSource(source: string, fallback: string): string {
    const value = String(source || '').trim();
    if (!value) return fallback;
    if (
      value.startsWith('http://') ||
      value.startsWith('https://') ||
      value.startsWith('data:') ||
      value.startsWith('blob:')
    ) {
      return value;
    }
    if (value.startsWith('/')) {
      return `${this.testAPI}${value}`;
    }
    if (value.includes('/')) {
      return `${this.testAPI}/${value.replace(/^\/+/, '')}`;
    }
    return `data:image/png;base64,${value}`;
  }

  private tryAutoGenerateReceipt(): void {
    if (
      this.autoGenerated ||
      !this.viewReady ||
      !this.userReady ||
      !this.receiptReady ||
      !this.receipt
    ) {
      return;
    }

    this.autoGenerated = true;
    setTimeout(() => this.generateReceipt(), 250);
  }
}
