import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnInit,
  ViewChild
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NavController } from '@ionic/angular';
import html2canvas from 'html2canvas'; // Import html2canvas
import { environment } from '../../environments/environment';
import { AuthService } from '../services/auth.service';
import { BookingService } from '../services/booking.service';
import { CompanyService } from '../services/company.service';
import { FormService } from '../services/form.service';
import { NetworkService } from '../services/network.service';
import { OfflineQueueService } from '../services/offline-queue.service';

@Component({
  selector: 'app-receipt-activity',
  templateUrl: './receipt-activity.page.html',
  styleUrls: ['./receipt-activity.page.scss'],
})
export class ReceiptActivityPage implements OnInit {
  @ViewChild('receiptContent') receiptContent!: ElementRef; // Reference to the content to capture
  receiptId: any;
  receipt: any;
  pdfUrl: string = '';
  isLocalOnly = false;

  localAPI = environment.API;
  uid: any; // Store the user ID
  user: any; // Object to hold user data
  companyProfile: any = null;
  private loadedCompanyId: number | null = null;
  private userReady = false;
  private viewReady = false;
  private receiptReady = false;
  private autoGenerated = false;
  private syncPollInterval: any = null;

  constructor(
    private activatedRoute: ActivatedRoute,
    private navCtrl: NavController,
    private authService: AuthService,
    private bookingService: BookingService,
    private companyService: CompanyService,
    private formService: FormService,
    private offlineQueue: OfflineQueueService,
    private networkService: NetworkService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit() {
    this.uid = this.authService.getUserId();
    this.activatedRoute.params.subscribe((params) => {
      this.receiptId = params['receipt_id'];

      console.log('Received ID:', this.receiptId);
      if (this.receiptId) {
        this.loadReceipt();
      } else {
        console.log('receipt id not found');

        // this.errorMessage = 'Receipt ID not found.';
        // this.isLoading = false;  // Hide loading spinner
      }
    });

    // this.loadForm();
    this.loadUser();
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
    this.tryAutoGenerateReceipt();
  }

  loadUser() {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      try {
        this.user = JSON.parse(storedUser);
      } catch {
        this.user = null;
      }
    }

    this.authService.refreshSession().subscribe({
      next: () => {
        this.user = this.authService.currentUser;
        this.uid = this.authService.getUserId();
        this.loadCompanyProfile(this.user?.company_id);
        this.userReady = true;
        this.tryAutoGenerateReceipt();
      },
      error: (error) => {
        console.log(error);
        this.userReady = true;
        this.tryAutoGenerateReceipt();
      },
    });
  }

  //get receipt details
  loadReceipt() {
    if (this.receiptId) {
      const stateBooking = history.state?.['booking'] ?? null;
      if (stateBooking) {
        this.isLocalOnly = stateBooking._isLocalOnly === true || !this.networkService.isOnline;
        this.receipt = this.mapBookingToReceipt(stateBooking);
        this.loadCompanyProfile(this.receipt?.company_id);
        this.receiptReady = true;
        if (this.isLocalOnly) {
          const idempotencyKey = history.state?.['idempotency_key'] ?? null;
          this.watchForSync(idempotencyKey);
        } else {
          this.tryAutoGenerateReceipt();
        }
        return;
      }

      this.bookingService.getBookingById(this.receiptId).subscribe(
        (response) => {
          const data = response?.data || response;
          if (data?.booking_type) {
            this.receipt = this.mapBookingToReceipt(data);
            this.loadCompanyProfile(this.receipt?.company_id);
            console.log('Loaded booking receipt:', this.receipt);
            this.receiptReady = true;
            this.tryAutoGenerateReceipt();
            return;
          }

          this.formService.getFormByID(this.receiptId).subscribe(
            (dataResponse) => {
              if (dataResponse.success && dataResponse.data) {
                this.receipt = dataResponse.data;
                console.log('Loaded receipt:', this.receipt);
                this.receiptReady = true;
                this.tryAutoGenerateReceipt();
              } else {
                console.error('Form data not found');
              }
            },
            (error) => {
              console.error('Error loading form:', error);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
          );
        },
        (error) => {
          console.error('Error loading booking receipt:', error);
          this.formService.getFormByID(this.receiptId).subscribe(
            (dataResponse) => {
              if (dataResponse.success && dataResponse.data) {
                this.receipt = dataResponse.data;
                console.log('Loaded receipt:', this.receipt);
                this.receiptReady = true;
                this.tryAutoGenerateReceipt();
              } else {
                console.error('Form data not found');
              }
            },
            (formError) => {
              console.error('Error loading form:', formError);
              this.receiptReady = true;
              this.tryAutoGenerateReceipt();
            },
          );
        },
      );
    } else {
      console.log('uid not found in storage');
    }
  }

  pdfLink: string = '';
  qrCodeReady: boolean = false;

  generateQR() {
    if (this.pdfUrl) {
      const pdfPath = this.pdfUrl.startsWith('http')
        ? this.pdfUrl
        : `${this.localAPI}${this.pdfUrl}`;
      // Link directly to the generated PDF so the QR opens the actual receipt file.
      this.pdfLink = pdfPath;
      this.qrCodeReady = true;
      this.cdr.detectChanges();
      console.log('Generating QR code with URL:', this.pdfLink);
    } else {
      alert('Error Generating PDF');
      console.log('No URL for QR code generation');
    }
  }

  getImageDataUrl(image: HTMLImageElement): string {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (ctx) {
      canvas.width = image.width;
      canvas.height = image.height;
      ctx.drawImage(image, 0, 0);
      return canvas.toDataURL('image/png');
    }
    return '';
  }

  // Method to generate the receipt PDF
  async generateReceipt() {
    console.log('generateReceipt() called');
    const receiptElement = this.receiptContent?.nativeElement as
      | HTMLElement
      | undefined; // Get the receipt content element
    if (!receiptElement) {
      alert('Error Generating PDF');
      console.error('Receipt element not found for capture');
      return;
    }

    console.log('Receipt element found, creating capture clone');
    const captureElement = this.createCaptureClone(receiptElement);
    document.body.appendChild(captureElement);

    try {
      await this.waitForImages(captureElement);
      console.log('Images wait completed');
    } catch (waitError) {
      console.warn(
        'Image wait timed out, continuing capture anyway',
        waitError,
      );
    }

    // Use html2canvas to capture a screenshot of the element
    console.log('Starting html2canvas capture');
    html2canvas(captureElement, {
      ignoreElements: (element) => {
        const tag = String(element?.tagName || '').toLowerCase();
        return (
          element.classList.contains('qr-btn') ||
          tag === 'ion-loading' ||
          tag === 'ion-backdrop' ||
          tag === 'ion-alert' ||
          tag === 'ion-toast' ||
          tag === 'ion-modal' ||
          tag === 'ion-popover'
        );
      },
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      scale: 2,
      imageTimeout: 15000,
    })
      .finally(() => {
        console.log('Canvas capture finally block, removing clone');
        captureElement.remove();
      })
      .then((canvas) => {
        console.log('Canvas captured successfully, converting to blob');
        canvas.toBlob((blob) => {
          if (blob) {
            console.log('Blob created, preparing FormData');
            // Prepare FormData to send the image file to the backend
            const formData = new FormData();
            formData.append('receiptImage', blob, 'receipt.png'); // Append Blob as file
            formData.append('receiptId', this.receiptId); // append receipt id as req

            console.log('FormData prepared, calling generatePdfFromImage API');
            // Send the formData to the backend API to generate the PDF
            this.formService.generatePdfFromImage(formData).subscribe(
              (response: any) => {
                console.log('API response received:', response);
                if (response.success) {
                  this.pdfUrl = response.fileUrl; // Save the returned PDF URL
                  this.generateQR(); // generate the QR Code
                  console.log('PDF URL:', this.pdfUrl);
                  // give the pdf url here
                } else {
                  alert('Error Generating PDF');
                  console.error('Failed to generate PDF', response);
                }
              },
              (error) => {
                alert('Error Generating PDF');
                console.error('Error generating PDF', {
                  status: error?.status,
                  message: error?.message,
                  error: error?.error,
                });
              },
            );
          } else {
            alert('Error Generating PDF');
            console.error('Failed to capture canvas as Blob');
          }
        }, 'image/png'); // Convert the canvas to a Blob in PNG format
      })
      .catch((error) => {
        alert('Error Generating PDF');
        console.error('Error capturing receipt:', {
          message: error?.message,
          stack: error?.stack,
          error,
        });
      });
  }

  private mapBookingToReceipt(record: any): any {
    const totalPax =
      Number(record?.total_pax || 0) ||
      Number(record?.domesticPax || record?.no_of_pax_domestik || 0) +
        Number(record?.internationalPax || record?.no_of_pax_antarbangsa || 0);

    const receiptId =
      record?.numericId ?? record?.id ?? this.receiptId ?? undefined;

    return {
      receipt_id: String(receiptId || ''),
      createdAt:
        record?.receipt_created_at ||
        record?.updated_at ||
        record?.created_at ||
        record?.updatedAt ||
        record?.createdAt,
      company_id: Number(record?.company_id ?? record?.companyId ?? 0) || null,
      activity_name: String(
        record?.product_name ||
          record?.productName ||
          record?.activity_name ||
          record?.activityName ||
          '',
      ),
      pax: totalPax,
      company_name: String(
        record?.company_name ||
          record?.companyName ||
          record?.company?.company_name ||
          '',
      ),
      location: String(
        record?.company_location ||
          record?.companyLocation ||
          record?.location ||
          record?.company?.location ||
          '',
      ),
      guest_name: String(
        record?.tourist_full_name ||
          record?.fullName ||
          record?.tourist_name ||
          record?.user_fullname ||
          record?.userFullname ||
          '',
      ),
      total_rm: Number(record?.total_price ?? record?.totalAmount ?? 0),
      status: String(record?.status || 'paid'),
      operator: {
        full_name: String(
          record?.operator_name ||
            record?.operatorName ||
            record?.user_fullname ||
            record?.userFullname ||
            '',
        ),
        business_name: String(
          record?.company_name ||
            record?.companyName ||
            record?.operator_name ||
            record?.operatorName ||
            '',
        ),
        user_email: String(
          record?.company_email ||
            record?.companyEmail ||
            record?.operatorEmail ||
            this.user?.user_email ||
            this.user?.email ||
            '',
        ),
      },
    };
  }

  get bookedByName(): string {
    return String(
      this.receipt?.guest_name ||
        this.receipt?.tourist_full_name ||
        this.receipt?.tourist_name ||
        'N/A',
    );
  }

  get exploreSabahLogoSrc(): string {
    return localStorage.getItem('explore_sabah_logo') || 'assets/icon/explore_sabah-without_bg.png';
  }

  get companyName(): string {
    const storedUser = localStorage.getItem('user');
    const cachedUser = storedUser ? JSON.parse(storedUser) : null;
    return String(
      this.companyProfile?.company_name ||
        this.receipt?.company_name ||
        this.user?.business_name ||
        this.user?.company?.company_name ||
        cachedUser?.company_name ||
        this.receipt?.operator?.business_name ||
        'N/A',
    );
  }

  get companyLocation(): string {
    const storedUser = localStorage.getItem('user');
    const cachedUser = storedUser ? JSON.parse(storedUser) : null;
    return String(
      this.companyProfile?.location ||
        this.companyProfile?.address ||
        this.receipt?.location ||
        this.user?.location ||
        this.user?.company?.location ||
        this.user?.business_address ||
        this.user?.company?.address ||
        cachedUser?.company_location ||
        'N/A',
    );
  }

  get companyEmail(): string {
    const storedUser = localStorage.getItem('user');
    const cachedUser = storedUser ? JSON.parse(storedUser) : null;
    return String(
      this.companyProfile?.email ||
        this.user?.company?.email ||
        this.user?.user_email ||
        this.user?.email ||
        this.receipt?.operator?.user_email ||
        cachedUser?.company_email ||
        cachedUser?.email ||
        'N/A',
    );
  }

  get companyLogoUrl(): string {
    const source =
      this.companyProfile?.operator_logo_image ||
      this.user?.company_logo ||
      this.user?.company?.operator_logo_image ||
      '';
    return this.resolveImageSource(source, 'assets/icon/RuralT Logo.png');
  }

  private createCaptureClone(sourceElement: HTMLElement): HTMLElement {
    const clone = sourceElement.cloneNode(true) as HTMLElement;
    clone.classList.add('receipt-capture-clone');
    clone.style.position = 'fixed';
    clone.style.left = '-10000px';
    clone.style.top = '0';
    // Force capture to a narrow portrait card width so the PDF shows a vertical card
    clone.style.width = '520px';
    clone.style.pointerEvents = 'none';
    clone.style.opacity = '1';

    clone
      .querySelectorAll('ion-button, qrcode, ion-header, ion-content')
      .forEach((el) => {
        el.remove();
      });

    clone.querySelectorAll('img').forEach((img) => {
      const source = (img as HTMLImageElement).getAttribute('src') || '';
      if (source) {
        (img as HTMLImageElement).crossOrigin = 'anonymous';
      }
    });

    const footerButton = clone.querySelector('.receipt-footer-button');
    if (footerButton) {
      footerButton.remove();
    }

    return clone;
  }

  private waitForImages(container: HTMLElement): Promise<void> {
    const images = Array.from(
      container.querySelectorAll('img'),
    ) as HTMLImageElement[];
    if (images.length === 0) {
      return Promise.resolve();
    }

    return Promise.race([
      Promise.all(
        images.map(
          (img) =>
            new Promise<void>((resolve) => {
              if (img.complete && img.naturalWidth > 0) {
                resolve();
                return;
              }
              img.onload = () => resolve();
              img.onerror = () => resolve();
            }),
        ),
      ).then(() => undefined),
      new Promise<void>((resolve) => setTimeout(resolve, 5000)),
    ]);
  }

  private unwrapPayload(response: any): any {
    return response?.data || response;
  }

  private loadCompanyProfile(companyId: any): void {
    const normalizedId = Number(companyId);
    if (!Number.isInteger(normalizedId) || normalizedId <= 0) {
      return;
    }
    if (this.loadedCompanyId === normalizedId) {
      return;
    }

    this.loadedCompanyId = normalizedId;
    this.companyService.getCompanyById(normalizedId).subscribe(
      (response) => {
        this.companyProfile = this.unwrapPayload(response);
      },
      (error) => {
        console.error('Error loading company profile:', error);
      },
    );
  }

  private resolveImageSource(source: string, fallback: string): string {
    const value = String(source || '').trim();
    if (!value) return fallback;
    if (
      value.startsWith('http://') ||
      value.startsWith('https://') ||
      value.startsWith('data:') ||
      value.startsWith('blob:')
    ) {
      return value;
    }
    if (value.startsWith('/')) {
      return `${this.localAPI}${value}`;
    }
    if (value.includes('/')) {
      return `${this.localAPI}/${value.replace(/^\/+/, '')}`;
    }
    return `data:image/png;base64,${value}`;
  }

  private tryAutoGenerateReceipt(): void {
    if (
      this.autoGenerated ||
      !this.viewReady ||
      !this.userReady ||
      !this.receiptReady ||
      !this.receipt ||
      this.isLocalOnly
    ) {
      console.log('tryAutoGenerateReceipt blocked:', {
        autoGenerated: this.autoGenerated,
        viewReady: this.viewReady,
        userReady: this.userReady,
        receiptReady: this.receiptReady,
        hasReceipt: !!this.receipt,
        isLocalOnly: this.isLocalOnly,
      });
      return;
    }

    console.log('tryAutoGenerateReceipt starting generateReceipt');
    this.autoGenerated = true;
    setTimeout(() => this.generateReceipt(), 250);
  }

  private watchForSync(idempotencyKey: string | null): void {
    if (!idempotencyKey) return;

    this.syncPollInterval = setInterval(async () => {
      const items = await this.offlineQueue.getAllQueueItems();
      const item = items.find((i) => i.idempotency_key === idempotencyKey);

      if (item?.server_booking_id) {
        clearInterval(this.syncPollInterval);
        this.syncPollInterval = null;
        this.receiptId = item.server_booking_id;
        this.isLocalOnly = false;
        this.autoGenerated = false;
        this.tryAutoGenerateReceipt();
      }
    }, 3000);
  }

  goBack(): void {
    this.navCtrl.back();
  }
}
