import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnInit,
  ViewChild,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import html2canvas from 'html2canvas'; // Import html2canvas
import { environment } from '../../environments/environment';
import { BookingService } from '../services/booking.service';
import { FormService } from '../services/form.service';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-receipt-package',
  templateUrl: './receipt-package.page.html',
  styleUrls: ['./receipt-package.page.scss'],
})
export class ReceiptPackagePage implements OnInit {
  @ViewChild('receiptContent') receiptContent!: ElementRef; // Reference to the content to capture
  receiptId: any;
  receipt: any;
  pdfUrl: string = '';

  testAPI = environment.API;
  localAPI = 'http://localhost:3000';
  uid: any; // Store the user ID
  user: any; // Object to hold user data
  packageDescArray: string[] = [];
  totalRM: number = 0;
  private userReady = false;
  private viewReady = false;
  private receiptReady = false;
  private autoGenerated = false;

  constructor(
    private activatedRoute: ActivatedRoute,
    private userService: UserService,
    private bookingService: BookingService,
    private formService: FormService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit() {
    this.uid = localStorage.getItem('uid'); // Retrieve user ID from local storage
    this.activatedRoute.params.subscribe((params) => {
      this.receiptId = params['receipt_id'];

      console.log('Received ID:', this.receiptId);
      if (this.receiptId) {
        this.loadReceipt();
      } else {
        console.log('receipt id not found');

        // this.errorMessage = 'Receipt ID not found.';
        // this.isLoading = false;  // Hide loading spinner
      }
    });

    // this.loadForm();
    this.loadUser();
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
    this.tryAutoGenerateReceipt();
  }

  loadUser() {
    if (this.uid) {
      this.userService.getUserByID(this.uid).subscribe(
        (data) => {
          this.user = data;
          this.userReady = true;
          if (this.receipt?.operator) {
            this.receipt.operator.user_email =
              this.user?.user_email || this.receipt.operator.user_email || '';
          }
          this.tryAutoGenerateReceipt();
          // console.log(data);
        },
        (error) => {
          console.log(error);
          this.userReady = true;
          this.tryAutoGenerateReceipt();
        },
      );
    } else {
      console.log('uid not found in storage');
      this.userReady = true;
      this.tryAutoGenerateReceipt();
    }
  }

  //get receipt details
  loadReceipt() {
    if (this.receiptId) {
      const stateBooking = history.state?.['booking'] ?? null;
      if (stateBooking) {
        this.applyBookingReceipt(stateBooking);
        return;
      }

      this.bookingService.getBookingById(this.receiptId).subscribe(
        (response) => {
          const data = response.data || response;
          if (data?.booking_type) {
            this.applyBookingReceipt(data);
            return;
          }

          this.loadLegacyReceipt();
        },
        (error) => {
          console.log(error);
          this.loadLegacyReceipt();
        },
      );
    } else {
      console.log('uid not found in storage');
    }
  }

  pdfLink: string = '';
  qrCodeReady: boolean = false;

  generateQR() {
    if (this.pdfUrl) {
      this.qrCodeReady = true;
      this.cdr.detectChanges();
      this.pdfLink = this.testAPI + this.pdfUrl;
      // this.pdfLink = this.localAPI + this.pdfUrl
      console.log('Generating QR code with URL:', this.pdfLink);
    } else {
      alert('Error Generating PDF');
      console.log('No URL for QR code generation');
    }
  }

  getImageDataUrl(image: HTMLImageElement): string {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (ctx) {
      canvas.width = image.width;
      canvas.height = image.height;
      ctx.drawImage(image, 0, 0);
      return canvas.toDataURL('image/png');
    }
    return '';
  }

  // Method to generate the receipt PDF
  generateReceipt() {
    const receiptElement = this.receiptContent.nativeElement; // Get the receipt content element

    // Use html2canvas to capture a screenshot of the element
    html2canvas(receiptElement, {
      ignoreElements: (element) => {
        const tag = String(element?.tagName || '').toLowerCase();
        return (
          element.classList.contains('qr-btn') ||
          tag === 'ion-loading' ||
          tag === 'ion-backdrop' ||
          tag === 'ion-alert' ||
          tag === 'ion-toast' ||
          tag === 'ion-modal' ||
          tag === 'ion-popover'
        );
      },
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      scale: 2,
    })
      .then((canvas) => {
        canvas.toBlob((blob) => {
          if (blob) {
            // Prepare FormData to send the image file to the backend
            const formData = new FormData();
            formData.append('receiptImage', blob, 'receipt.png'); // Append Blob as file
            formData.append('receiptId', this.receiptId); // append receipt id as req

            // Send the formData to the backend API to generate the PDF
            this.formService.generatePdfFromImage(formData).subscribe(
              (response: any) => {
                if (response.success) {
                  this.pdfUrl = response.fileUrl; // Save the returned PDF URL
                  this.generateQR(); // generate the QR Code
                  console.log('PDF URL:', this.pdfUrl);
                  // give the pdf url here
                } else {
                  alert('Error Generating PDF');
                  console.error('Failed to generate PDF');
                }
              },
              (error) => {
                alert('Error Generating PDF');
                console.error('Error generating PDF', error);
              },
            );
          } else {
            alert('Error Generating PDF');
            console.error('Failed to capture canvas as Blob');
          }
        }, 'image/png'); // Convert the canvas to a Blob in PNG format
      })
      .catch((error) => {
        alert('Error Generating PDF');
        console.error('Error capturing receipt:', error);
      });
  }

  private loadLegacyReceipt(): void {
    this.formService.getFormByID(this.receiptId).subscribe(
      (response) => {
        const data = response.data || response;
        this.receipt = data;
        this.packageDescArray = [];
        this.totalRM = 0;
        console.log('Receipt data:', this.receipt);
        console.log('Operator data:', this.receipt.operator);
        console.log('Package data:', data.package);

        if (typeof data.package === 'string') {
          try {
            const packageArray = JSON.parse(data.package);
            this.packageDescArray = packageArray.map(
              (item: { packageDesc: any }) => item.packageDesc,
            );
            this.totalRM = packageArray.reduce(
              (sum: any, item: { total_rm: any }) => sum + item.total_rm,
              0,
            );
          } catch (error) {
            console.error('Error parsing package data:', error);
          }
        } else if (Array.isArray(data.package)) {
          const packageArray = data.package;
          this.packageDescArray = packageArray.map(
            (item: { packageDesc: any }) => item.packageDesc,
          );
          this.totalRM = packageArray.reduce(
            (sum: any, item: { total_rm: any }) => sum + item.total_rm,
            0,
          );
        } else {
          console.error('Unexpected data format for package:', data.package);
        }

        this.receiptReady = true;
        this.tryAutoGenerateReceipt();
      },
      (error) => {
        console.log(error);
        this.receiptReady = true;
        this.tryAutoGenerateReceipt();
      },
    );
  }

  private applyBookingReceipt(record: any): void {
    const packageItems = Array.isArray(record?.package_companies)
      ? record.package_companies
      : [];

    this.receipt = {
      receipt_id: String(record?.id || this.receiptId || ''),
      createdAt:
        record?.receipt_created_at || record?.updated_at || record?.created_at,
      operator: {
        business_name: String(
          record?.company_name || record?.operator_name || '',
        ),
        full_name: String(record?.operator_name || record?.user_fullname || ''),
        user_email: String(this.user?.user_email || ''),
      },
      package: packageItems.map((item: any) => ({
        packageDesc: String(item?.description || item?.referral_company || ''),
        total_rm: Number(item?.per_price || 0),
      })),
    };

    this.packageDescArray = packageItems.map((item: any, index: number) =>
      String(
        item?.description || item?.referral_company || `Item ${index + 1}`,
      ),
    );
    this.totalRM = packageItems.reduce(
      (sum: number, item: any) => sum + Number(item?.per_price || 0),
      0,
    );
    this.receiptReady = true;
    this.tryAutoGenerateReceipt();
  }

  private tryAutoGenerateReceipt(): void {
    if (
      this.autoGenerated ||
      !this.viewReady ||
      !this.userReady ||
      !this.receiptReady ||
      !this.receipt
    ) {
      return;
    }

    this.autoGenerated = true;
    setTimeout(() => this.generateReceipt(), 250);
  }
}
