import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  OnInit,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NavController } from '@ionic/angular';
import { environment } from '../../environments/environment';
import { AuthService } from '../services/auth.service';
import { BookingService } from '../services/booking.service';
import { CompanyService } from '../services/company.service';
import { FileUrlService } from '../services/file-url.service';
import { FormService } from '../services/form.service';
import { NetworkService } from '../services/network.service';
import { OfflineQueueService } from '../services/offline-queue.service';

@Component({
  selector: 'app-receipt-package',
  templateUrl: './receipt-package.page.html',
  styleUrls: ['./receipt-package.page.scss'],
})
export class ReceiptPackagePage implements OnInit, AfterViewInit {
  receiptId: any;
  receipt: any;
  pdfUrl: string = '';
  isLocalOnly = false;

  localAPI = environment.API;
  uid: any; // Store the user ID
  user: any; // Object to hold user data
  companyProfile: any = null;
  private loadedCompanyId: number | null = null;
  packageDescArray: string[] = [];
  totalRM: number = 0;
  private userReady = false;
  private viewReady = false;
  private receiptReady = false;
  private autoGenerated = false;
  private syncPollInterval: any = null;

  constructor(
    private activatedRoute: ActivatedRoute,
    private navCtrl: NavController,
    private authService: AuthService,
    private bookingService: BookingService,
    private companyService: CompanyService,
    private formService: FormService,
    private offlineQueue: OfflineQueueService,
    private networkService: NetworkService,
    private cdr: ChangeDetectorRef,
    private fileUrlService: FileUrlService,
  ) {}

  ngOnInit() {
    this.uid = this.authService.getUserId();
    this.activatedRoute.params.subscribe((params) => {
      this.receiptId = params['receipt_id'];

      console.log('Received ID:', this.receiptId);
      if (this.receiptId) {
        this.loadReceipt();
      } else {
        console.log('receipt id not found');

        // this.errorMessage = 'Receipt ID not found.';
        // this.isLoading = false;  // Hide loading spinner
      }
    });

    // this.loadForm();
    this.loadUser();
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
    this.tryAutoGenerateReceipt();
  }

  loadUser() {
    const storedUserRaw = localStorage.getItem('user');
    if (storedUserRaw) {
      try {
        const parsed = JSON.parse(storedUserRaw);
        this.user = parsed?.data?.user || parsed;
        this.uid =
          this.user?.id ||
          this.user?.unified_user_id ||
          this.uid;
        this.loadCompanyProfile(this.user?.company_id);
      } catch (error) {
        console.warn('Failed to parse cached user from localStorage', error);
      }
    }

    if (!this.authService.isAuthenticated) {
      this.userReady = true;
      this.tryAutoGenerateReceipt();
      return;
    }

    this.authService.refreshSession().subscribe({
      next: () => {
        this.user = this.authService.currentUser || this.user;
        this.uid =
          this.authService.getUserId() ||
          this.user?.id ||
          this.user?.unified_user_id ||
          this.uid;
        this.loadCompanyProfile(this.user?.company_id);
        this.userReady = true;
        this.tryAutoGenerateReceipt();
      },
      error: (error) => {
        console.log(error);
        this.userReady = true;
        this.tryAutoGenerateReceipt();
      },
    });
  }

  //get receipt details
  loadReceipt() {
    if (this.receiptId) {
      const stateBooking = history.state?.['booking'] ?? null;
      if (stateBooking) {
        this.isLocalOnly = stateBooking._isLocalOnly === true || !this.networkService.isOnline;
        this.receipt = this.mapBookingToReceipt(stateBooking);
        this.loadCompanyProfile(this.receipt?.company_id);
        this.syncPackageSummary();
        this.receiptReady = true;
        // The QR/PDF endpoint needs a numeric server booking id. If we only
        // have the local UUID so far, poll for the synced server id before
        // generating the receipt (covers offline and not-yet-synced online).
        const hasNumericId = /^\d+$/.test(String(this.receiptId));
        if (this.isLocalOnly || !hasNumericId) {
          const idempotencyKey = history.state?.['idempotency_key'] ?? null;
          this.watchForSync(idempotencyKey);
        } else {
          this.tryAutoGenerateReceipt();
        }
        return;
      }

      this.bookingService.getBookingById(this.receiptId).subscribe(
        (response) => {
          const data = response.data || response;
          if (data?.booking_type) {
            this.receipt = this.mapBookingToReceipt(data);
            this.loadCompanyProfile(this.receipt?.company_id);
            this.syncPackageSummary();
            this.receiptReady = true;
            this.tryAutoGenerateReceipt();
            return;
          }

          this.loadLegacyReceipt();
        },
        (error) => {
          console.log(error);
          this.loadLegacyReceipt();
        },
      );
    } else {
      console.log('uid not found in storage');
    }
  }

  pdfLink: string = '';
  qrCodeReady: boolean = false;

  generateReceipt() {
    const id = this.receipt?.receipt_id || this.receiptId;
    if (!id) {
      console.error('No receipt ID for PDF generation');
      return;
    }
    this.pdfLink = this.bookingService.getReceiptPdfUrl(id);
    this.pdfUrl = this.pdfLink;
    this.qrCodeReady = true;
    this.cdr.detectChanges();
    console.log('%c[Receipt PDF] Open in browser:', 'color:#2e7d32;font-weight:bold;', this.pdfLink);
  }

  private loadLegacyReceipt(): void {
    this.formService.getFormByID(this.receiptId).subscribe(
      (response) => {
        const data = response.data || response;
        this.receipt = data;
        this.receipt.customer_type =
          this.receipt.customer_type || this.receipt.customerType || 'tourist';
        this.packageDescArray = [];
        this.totalRM = 0;
        console.log('Receipt data:', this.receipt);
        console.log('Operator data:', this.receipt.operator);
        console.log('Package data:', data.package);

        if (typeof data.package === 'string') {
          try {
            const packageArray = JSON.parse(data.package);
            this.packageDescArray = packageArray.map(
              (item: { packageDesc: any }) => item.packageDesc,
            );
            this.totalRM = packageArray.reduce(
              (sum: any, item: { total_rm: any }) => sum + item.total_rm,
              0,
            );
          } catch (error) {
            console.error('Error parsing package data:', error);
          }
        } else if (Array.isArray(data.package)) {
          const packageArray = data.package;
          this.packageDescArray = packageArray.map(
            (item: { packageDesc: any }) => item.packageDesc,
          );
          this.totalRM = packageArray.reduce(
            (sum: any, item: { total_rm: any }) => sum + item.total_rm,
            0,
          );
        } else {
          console.error('Unexpected data format for package:', data.package);
        }

        this.receiptReady = true;
        this.tryAutoGenerateReceipt();
      },
      (error) => {
        console.log(error);
        this.receiptReady = true;
        this.tryAutoGenerateReceipt();
      },
    );
  }

  private mapBookingToReceipt(record: any): any {
    const packageItems = Array.isArray(record?.package_companies)
      ? record.package_companies
      : [];

    const totalPax =
      Number(record?.total_pax || 0) ||
      Number(record?.domesticPax || record?.no_of_pax_domestik || 0) +
        Number(record?.internationalPax || record?.no_of_pax_antarbangsa || 0);

    const receiptId =
      record?.numericId ?? record?.id ?? this.receiptId ?? undefined;

    return {
      receipt_id: String(receiptId || ''),
      createdAt:
        record?.receipt_created_at ||
        record?.updated_at ||
        record?.created_at ||
        record?.updatedAt ||
        record?.createdAt,
      company_id: Number(record?.company_id ?? record?.companyId ?? 0) || null,
      customer_type: String(
        record?.customer_type || record?.customerType || 'tourist',
      )
        .toLowerCase()
        .trim(),
      guest_name: String(
        record?.tourist_full_name ||
          record?.fullName ||
          record?.tourist_name ||
          record?.user_fullname ||
          record?.userFullname ||
          '',
      ),
      pax: totalPax,
      status: String(record?.status || 'paid'),
      total_rm: Number(record?.total_price ?? record?.totalAmount ?? 0),
      package_items: packageItems.map((item: any, index: number) => ({
        description: String(
          item?.description ||
            item?.service_name ||
            item?.serviceName ||
            item?.referral_company ||
            item?.referee_company ||
            `Item ${index + 1}`,
        ),
        per_price: Number(item?.per_price || item?.perPrice || 0),
      })),
      operator: {
        business_name: String(
          record?.company_name ||
            record?.companyName ||
            record?.operator_name ||
            record?.operatorName ||
            '',
        ),
        full_name: String(
          record?.operator_name ||
            record?.operatorName ||
            record?.user_fullname ||
            record?.userFullname ||
            '',
        ),
        user_email: String(
          this.user?.user_email ||
            this.user?.email ||
            record?.operatorEmail ||
            '',
        ),
      },
    };
  }

  private syncPackageSummary(): void {
    const items = Array.isArray(this.receipt?.package_items)
      ? this.receipt.package_items
      : [];

    this.packageDescArray = items.map((item: any, index: number) =>
      String(item?.description || `Item ${index + 1}`),
    );
    const bookingTotal = Number(this.receipt?.total_rm ?? 0);
    this.totalRM =
      Number.isFinite(bookingTotal) && bookingTotal > 0
        ? bookingTotal
        : items.reduce(
            (sum: number, item: any) => sum + Number(item?.per_price || 0),
            0,
          );
  }

  get customerType(): string {
    return String(
      this.receipt?.customer_type || this.receipt?.customerType || 'tourist',
    )
      .toLowerCase()
      .trim();
  }

  get bookedByLabel(): string {
    return this.customerType === 'company'
      ? 'NAMA SYARIKAT/COMPANY NAME'
      : 'DITEMPAH OLEH/BOOKED BY';
  }

  get bookedByName(): string {
    return String(
      this.receipt?.guest_name ||
        this.receipt?.tourist_full_name ||
        this.receipt?.tourist_name ||
        'N/A',
    );
  }

  get exploreSabahLogoSrc(): string {
    return localStorage.getItem('explore_sabah_logo') || 'assets/icon/explore_sabah-without_bg.png';
  }

  get companyName(): string {
    const storedUser = localStorage.getItem('user');
    const cachedUser = storedUser ? JSON.parse(storedUser) : null;
    return String(
      this.companyProfile?.company_name ||
        this.receipt?.company_name ||
        this.user?.business_name ||
        this.user?.company?.company_name ||
        cachedUser?.company_name ||
        this.receipt?.operator?.business_name ||
        'N/A',
    );
  }

  // "Issued By" uses the operator who created the booking (same as the booking
  // confirmation PDF). Falls back to the company name when no operator name is
  // recorded.
  get issuedByName(): string {
    const operatorName = String(
      this.receipt?.operator?.full_name ||
        this.receipt?.operator_name ||
        '',
    ).trim();
    return operatorName || this.companyName;
  }

  get companyEmail(): string {
    const storedUser = localStorage.getItem('user');
    const cachedUser = storedUser ? JSON.parse(storedUser) : null;
    return String(
      this.companyProfile?.email ||
        this.user?.company?.email ||
        this.user?.user_email ||
        this.user?.email ||
        this.receipt?.operator?.user_email ||
        cachedUser?.company_email ||
        cachedUser?.email ||
        'N/A',
    );
  }

  get companyLogoUrl(): string {
    const source =
      this.companyProfile?.operator_logo_image ||
      this.user?.company_logo ||
      this.user?.company?.operator_logo_image ||
      '';
    const resolved = this.fileUrlService.resolve(source, {
      base64MimeType: 'image/png',
    });
    return resolved || 'assets/icon/RuralT Logo.png';
  }

  private unwrapPayload(response: any): any {
    return response?.data || response;
  }

  private loadCompanyProfile(companyId: any): void {
    const normalizedId = Number(companyId);
    if (!Number.isInteger(normalizedId) || normalizedId <= 0) {
      return;
    }
    if (this.loadedCompanyId === normalizedId) {
      return;
    }

    this.loadedCompanyId = normalizedId;
    this.companyService.getCompanyById(normalizedId).subscribe(
      (response) => {
        this.companyProfile = this.unwrapPayload(response);
      },
      (error) => {
        console.error('Error loading company profile:', error);
      },
    );
  }

  private tryAutoGenerateReceipt(): void {
    if (
      this.autoGenerated ||
      !this.viewReady ||
      !this.userReady ||
      !this.receiptReady ||
      !this.receipt ||
      this.isLocalOnly
    ) {
      return;
    }

    this.autoGenerated = true;
    setTimeout(() => this.generateReceipt(), 250);
  }

  private watchForSync(idempotencyKey: string | null): void {
    if (!idempotencyKey) return;

    this.syncPollInterval = setInterval(async () => {
      const items = await this.offlineQueue.getAllQueueItems();
      const item = items.find((i) => i.idempotency_key === idempotencyKey);

      if (item?.server_booking_id) {
        clearInterval(this.syncPollInterval);
        this.syncPollInterval = null;
        this.receiptId = item.server_booking_id;
        this.isLocalOnly = false;
        this.autoGenerated = false;
        // Re-fetch the synced server record so the receipt date (created_at)
        // and any server-computed fields are populated, then generate the QR.
        this.bookingService.getBookingById(String(item.server_booking_id)).subscribe(
          (response) => {
            const data = response?.data || response;
            if (data?.booking_type) {
              this.receipt = this.mapBookingToReceipt(data);
              this.loadCompanyProfile(this.receipt?.company_id);
              this.syncPackageSummary();
            }
            this.tryAutoGenerateReceipt();
          },
          () => this.tryAutoGenerateReceipt(),
        );
      }
    }, 3000);
  }

  formatMyDate(dateStr: string | null | undefined): string {
    if (!dateStr) return '-';
    const months = [
      'JANUARI', 'FEBRUARI', 'MAC', 'APRIL', 'MEI', 'JUN',
      'JULAI', 'OGOS', 'SEPTEMBER', 'OKTOBER', 'NOVEMBER', 'DISEMBER',
    ];
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return '-';
    const day = String(d.getDate()).padStart(2, '0');
    return `${day} ${months[d.getMonth()]} ${d.getFullYear()}`;
  }

  goBack(): void {
    this.navCtrl.back();
  }
}
